name: hexlet-check

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
           python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
            python -m pip install --upgrade pip
            pip install flake8 pytest poetry
      - name: Run linter
          run: poetry run flake8 gendiff
      - name: Run tests
          run: poetry run pytest --cov-report xml
      - name: Hexlet project check
        uses: hexlet/project-action@release
