name: hexlet-check

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Hexlet project check
        uses: hexlet/python-project-lvl2-action@release

      - name: 'test'
        run: make run_tests

      - name: 'linter'
        run: make linter

